### ISSUE TITLE
Operand Specifier decimal value

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#108]
The decimal value of the Operand Specifier field should be unsigned. Note that the Operand field is correctly rendered as signed.
<img width="348" alt="OprndSpec-decimal" src="https://user-images.githubusercontent.com/6937032/86491688-3e4c1c80-bd20-11ea-865d-618e056376e5.png">

**Comment by Matthew-McRaven** [comment]
Better with 49451f244b7352005481042be8960b025e27caef?

**Comment by StanWarford** [comment]
Fixed
