### ISSUE TITLE
Bug: extra column in ASCII memory view?

### ISSUE THREAD

**Issue by fstonedahl** [StanWarford/pep9suite#116]
At least on Linux (haven't checked other OSs), it appears to me that the ASCII view of main memory has 9 columns of characters, when it should only have 8 columns.

**Comment by fstonedahl** [comment]
Update: here's an image showing the bug.  

![image](https://user-images.githubusercontent.com/770633/158505095-ee79e9dc-ec07-4310-8184-f5a951a5a01d.png)

Notice the duplicated values in the 9th column vs 1st column of the next row...

**Comment by Matthew-McRaven** [comment]
Good eye! I've already put together a fix for our next big release

**Comment by Matthew-McRaven** [comment]
Fixed in v9.4.1
