### ISSUE TITLE
More permissive Pep/9 object code loader?

### ISSUE THREAD

**Issue by fstonedahl** [StanWarford/pep9suite#120]
Would there be any objection to making the Pep/9 loader more permissive about input format, and accept object codes that don't have spaces between bytes, like:  `C10004` instead of `C1 00 04`?  

Reason 1) The Pep/9 Assembler Listing currently formats object code that way, so I think it would be logical if Pep/9 also accepted it in that format.
Reason 2) It would make it much more feasible for students to write a [quine](https://en.wikipedia.org/wiki/Quine_(computing)) in Pep/9 **object code**, which I think would be an interesting/clever assignment to give students to make them think about instructions vs data.  

Currently, as far as I can tell, the default Pep/9 OS doesn't provide any simple way to print hex output with spaces between each byte?  HEXO appears to always output 4 digits without spaces  (`ABCD`, and not `AB CD`), and I don't know of anyway to output just a single hex byte, short of writing a whole custom function that replicates most of the behavior of the HEXO trap.  And doing that in machine language would be quite painful.  Furthermore, pedagogically, I'd like to be able to assign the `quine` program after Chapter 4 or 5 in the book, without students having to use any features from Chapter 6 or later.

On a related note, I think it would be nice if the loader popped up an error message whenever it saw a string of hex digits with an odd length, since that would be a half-byte (surely a student error), or if it sees any non-hex-digit characters (other than "zz").

**Comment by Matthew-McRaven** [comment]
We are thinking the next Pep loader will feature a couple of changes:

1. The loader will work with or without whitespace.
2. The object code pane will block users from entering any non-hex digit (or zZ)
3. I can count the number of object code characters and ensure that count%2==0.

**Comment by StanWarford** [comment]
We can do this for Pep/10. The loader for Pep/9 cannot be changed, as that would alter some of the published machine vectors, which would make the software incompatible with the fifth edition of the textbook — not to mention that the loader itself would be incompatible.
—Stan

**Comment by Matthew-McRaven** [comment]
This is true--any change to the OS can only be made to Pep/10. In fact, most changes suggested here will first land in Pep/10 and be back ported.
