### ISSUE TITLE
memory visualizer text overlap

### ISSUE THREAD

**Issue by fstonedahl** [StanWarford/pep9suite#122]
With long variable names for global arrays, the words can overlap with the stack memory addresses -- there's no need for this, since there is plenty of whitespace room on either side, so maybe just separate the global memory & stack a little more horizontally?  Screenshot:

![image](https://user-images.githubusercontent.com/770633/163243648-0cff5567-6f7a-4597-8b29-4ccaba4917f2.png)

**Comment by Matthew-McRaven** [comment]
WIth the way this is rendered, I have to do offsets in pixels. So, I've added 50px between columns, giving the below image.
![image](https://user-images.githubusercontent.com/35609985/200145588-a0a6265a-5a16-40bb-8fdd-13602dac8082.png)

**Comment by Matthew-McRaven** [comment]
If you're happy with this setup, a5eb545058f9485d537e48b8877fd0a603c61aea contains these fixes.

**Comment by StanWarford** [comment]
👍Sent from my iPhoneThis message has been intercepted by the NSA: The only part of government that actually listens.On Nov 5, 2022, at 4:14 PM, Matthew McRaven ***@***.***> wrote:﻿
If you're happy with this setup, a5eb545 contains these fixes.
