### ISSUE TITLE
Local Array Memory Visualization Indices backward

### ISSUE THREAD

**Issue by fstonedahl** [StanWarford/pep9suite#124]
Load Figure 6.36 from the help menu, and start debugging. 

![image](https://user-images.githubusercontent.com/770633/164498928-b8f6d8b3-00aa-4f60-91c0-ae0c6c877430.png)

(See how the vector array indices are getting larger going *up* the stack?  It should be the opposite).

**Comment by Matthew-McRaven** [comment]
![image](https://user-images.githubusercontent.com/35609985/200144513-81961467-9ab9-4143-b188-6e50128090ff.png)
@StanWarford, this updated version looks correct to you?

**Comment by StanWarford** [comment]
👍Sent from my iPhoneThis message has been intercepted by the NSA: The only part of government that actually listens.On Nov 5, 2022, at 3:59 PM, Matthew McRaven ***@***.***> wrote:﻿

@StanWarford, this updated version looks correct to you?

**Comment by StanWarford** [comment]
Are we ready to do a release of this? Can we do a build and let me test it?

**Comment by Matthew-McRaven** [comment]
Fixed in v9.4.1
