### ISSUE TITLE
Pep/9 crashing more often?

### ISSUE THREAD

**Issue by fstonedahl** [StanWarford/pep9suite#128]
My students seem to be having Pep/9 (the latest released version for Windows) crash more often than I remember from past years.

Some students told me that it happens most often when they choose "Assemble and Format", but the assembly code was not correct (maybe wrong syntax somewhere?). 

I haven't tracked it down to confirm this, or to find a small reproducible example yet... but it is very frustrating to students when they've typed in a bunch of code and then the program crashes and they have to type it in again. (I am now encouraging them to "Save source" early and often, but...)

**Comment by Matthew-McRaven** [comment]
Looks like wrong assembly syntax in some cases can trigger a CTD. In the mean time, save before formatting source.

Fix looks rather simple. I'll try and put together a release over the weekend (v9.4.2).

Sorry for the inconvenience.

**Comment by Matthew-McRaven** [comment]
I believe I have caught the bug causing CTD on "Assemble and Format".

A release is posted [here](https://github.com/StanWarford/pep9suite/releases/tag/v9.4.2). 

Please let me know if this resolves the issues your students are seeing.
