### ISSUE TITLE
Document installer creation externally

### ISSUE THREAD

**Issue by Matthew-McRaven** [StanWarford/pep9suite#53]
Currently, the process for creating an installer is fairly well documented. However, this documentation resides within the installer creation files, and as such might not be readily noticeable by most users.

There is a work in progress page on the wiki that needs to be completed, and should include pictures and directions for how to properly set the compiler flags.

**Comment by Matthew-McRaven** [comment]
Also add instructions to the mac installer for how to allow Pep apps to run, as they are released from untrusted developers. Alternatively, look into automating signing of applications as part of dmg installer generation.

**Comment by Matthew-McRaven** [comment]
Resolved with https://github.com/StanWarford/pep9suite/wiki/Building-Installers-from-Sources.
Still need to add signing, but this will be added later today.

**Comment by Matthew-McRaven** [comment]
Upon further investigation into codesigning on Mac, I have decided against signing our applications.

Since I would manually have to recurse through the frameworks and libraries and sign them, it is a significant time investment to write this script.

We currently ship unsigned files, and I suggest we continue to ship unsigned files.

If someone wants to make this work in the future, see [Apple's website on signing](https://developer.apple.com/library/archive/technotes/tn2206/_index.html).

**Comment by StanWarford** [comment]
I agee. I download a ton of apps that are unsigned, especially educational apps.
