### ISSUE TITLE
Differences between new Pep9 and old Pep9

### ISSUE THREAD

**Issue by Matthew-McRaven** [StanWarford/pep9suite#56]
In working on #55, I noticed a couple of discrepancies between the new version Pep9 and currently posted version of Pep9.
**Start debugging is pressed**
- Old Pep9 loads whatever object code is in the object code pane will be loaded into memory. If a user modifies the object code but not the source file, the simulator will attempt to step through the original source program's text, but this source code is not what is actually loaded in memory. 
- New Pep9 unconditionally reassembles the user program, loads it into memory, then begins debugging. There is no chance for a discrepancy to arise between the object code pane and the assembled program's object code output.

**Pane switching on start debugging object**
- Old Pep9 leaves the user on whatever pane they currently have selected.
- New Pep9 unconditionally switches the user to the debugger tab.
- Do we need some new way of representing object code debugging? Should we hide the memory & program traces in their entirety? This might be something to discuss for Pep10.

@StanWarford any thoughts on which behaviors are preferable?

**Comment by StanWarford** [comment]
Start debugging is pressed: I would take it one notch higher and say when Start Debugging is pressed, first clear memory then assemble, load, and start debugging. This would remove a major irritant I have in lecture when I demo a program twice and have leftover values displayed from the previous run.
Pane switching on Start Debugging Object: I like the old behavior. Again, I would take it one notch higher and say you should not be able to see the debugger tab at all! When you debug object, the assumption is that the assembler source either does not exist or is irrelevant. This would allow the user to assemble, modify object, and trace modified object.

**Comment by Matthew-McRaven** [comment]
Start debugging should do all those things. No leftover values are left in
memory or the CPU.

I would like to have a discussion with you about how to best format an
assembly project. Could we follow up on that over email or phone call?
