### ISSUE TITLE
pep9asm Copy to Object does not clear source

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#57]
If you have a current project with content in Source, Object, and Listing pane, then go to Help and do a Copy to Object from a Chapter 4 example, the Source and Listing panes should be cleared. Correct behavior in current release. Related issue, when you copy to source the existing object and listing panes should be cleared.

**Comment by StanWarford** [comment]
Another related issue: the same behavior happens when you open a new file with an existing project.

**Comment by Matthew-McRaven** [comment]
I have a fix incoming for this. It constitutes a near rewrite of the assembler, object, and listing panes. 
While a smaller patch could have fixed this issue, my refactor allows for several assembler panes to exist in the application at once, which is a prerequisite for Pep10.

The refactor doesn't have any obvious bugs, but I would appreciate if you could thoroughly test any interactions with the source, object, and listing panes.

**Comment by Matthew-McRaven** [comment]
Check out 870a3cb56921bb9dfb2722761e5e4e5f58e727f0. This should fix this issue.

**Comment by StanWarford** [comment]
Looks good. However, when you Copy to Source or open a new file, the Input and Output panes need to be cleared.

**Comment by Matthew-McRaven** [comment]
Fixed Pep9asm/Pep9Micro's behavior with d316275230750426a9ef0136492a748de19848ee.
