### ISSUE TITLE
pep9asm source code pane gutter

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#58]
There is a source code pane gutter in pep9asm. See figure:
<img width="211" alt="pep9asm-source-code-pane" src="https://user-images.githubusercontent.com/6937032/57201148-9edba000-6f49-11e9-8311-ddca81fb9e1d.png">

**Comment by Matthew-McRaven** [comment]
Hello,

This is working as intended. This is the area for breakpoints. Try clicking
on an executable line.

Matthew

**Comment by Matthew-McRaven** [comment]
@StanWarford this behavior is modeled after the Qt and Visual Studio IDE’s.

Take a look at the text editor in Pep9CPU. In this app, I include line
numbers for the microcode to make finding entries in the object code pane
easier.

**Comment by StanWarford** [comment]
Oops, my mistake!
