### ISSUE TITLE
pep9asm Debugger tab layout

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#59]
The Program Trace pane and Memory Trace pane are different widths, have different heading styles, and different borders. They should be identical to Input and Output styles. (1) Too much space below Program Trace label. (2) Memory Trace pane needs a thin border line. (3) Program Trace pane needs to be wider. (4) Need a splitter between the Program Trace and Memory Trace.
<img width="622" alt="Debugger-Tab" src="https://user-images.githubusercontent.com/6937032/57330419-d45bc700-70ca-11e9-819c-5c13a9972b96.png">

**Comment by Matthew-McRaven** [comment]
@StanWarford how do you like the look an feel of the pane?

**Comment by StanWarford** [comment]
Items (3) and (4) are fixed. It appears that items (1) and (2) are still present. Namely, space under Program Trace label and absence of thin border around Memory Trace.

**Comment by Matthew-McRaven** [comment]
(1) is fixed with b904859fecf25d5f3edb2adcbc5772fa10da2895.

**Comment by Matthew-McRaven** [comment]
(2) is fixed with 0eb9f9774732f3e2974dbe115196143e4d2a1a40.

**Comment by StanWarford** [comment]
(3) Seems to have re-appeared!

**Comment by Matthew-McRaven** [comment]
(3) fixed on Mac & Windows by 6864a05ae368bccf7cbcf965440a9d47b76447f9.

**Comment by Matthew-McRaven** [comment]
@StanWarford is this resolved to your liking?

**Comment by StanWarford** [comment]
Looks good!
