### ISSUE TITLE
pep9asm Help figure display bug

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#60]
There are some extraneous characters in some object code displays that are not in the files.
<img width="539" alt="Help-Fig-Display-bug" src="https://user-images.githubusercontent.com/6937032/57335404-59e57400-70d7-11e9-979f-54afec9ef7f7.png">

**Comment by Matthew-McRaven** [comment]
I think this bug is fixed by 6bf1afcc0250b103c6fd6a7cf94a86fcf4a0ca7b, can you verify that this bug is fixed?

**Comment by StanWarford** [comment]
Fixed.
