### ISSUE TITLE
Memory dump style

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#61]
Request to change memory dump format to match style of textbook. (1) Addresses not prefixed with 0x. (2) Hex characters uppercase. (3) Two vertical line separators as in old pep9.
<img width="186" alt="memory-dump-style" src="https://user-images.githubusercontent.com/6937032/57472324-0fccd180-7242-11e9-9be7-edb13159efa2.png">

**Comment by Matthew-McRaven** [comment]
I believe this is fixed as of e84bb3dfbd022fad3f5b3c2eec7df05a46c5b0c0. Let me know if this looks right to you.

**Comment by StanWarford** [comment]
Looks good. Can you put a little space on both sides of the divider between the address and memory?

**Comment by Matthew-McRaven** [comment]
Was this fixed in 460f300b484c1c51178cd8bee33c396a0a388251?

**Comment by StanWarford** [comment]
Much better. How hard would it be to decrease the space to the right of the left separator so that there is equal spacing on both sides of the separator?
<img width="265" alt="memory-dump" src="https://user-images.githubusercontent.com/6937032/57502754-fc515300-72a1-11e9-9ed0-3b629b0528e8.png">

**Comment by Matthew-McRaven** [comment]
Is this better with ed35a92b6dbe14433b61b5a574e189f024ee17c2?

**Comment by StanWarford** [comment]
Better. Sorry to be so picky. If this is difficult, don't bother. But, a tad too much space on left side of left separator. See pic below.
<img width="421" alt="memory-dump-2" src="https://user-images.githubusercontent.com/6937032/57547945-9356f300-7314-11e9-8f37-78e45118f970.png">

**Comment by Matthew-McRaven** [comment]
It should be closer in de1aa856842f515fa366b49e8eaf3dec3856859a. As I'm doing pixel arithmetic based on font sizes, I can't guarantee identical spacing in general, but this should be slightly closer.

**Comment by Matthew-McRaven** [comment]
@StanWarford does this work as desired now?

**Comment by StanWarford** [comment]
Looks the same as my latest pic, but that's ok.

**Comment by Matthew-McRaven** [comment]
The widget has different rendering behavior on windows than mac (see attached images), so Might chalk up the slight inaccuracy to that.

Mac, selection spans all available space:
![Screen Shot 2019-05-14 at 7 58 07 PM](https://user-images.githubusercontent.com/35609985/57745595-a3f3ca00-7682-11e9-9bc8-162d37886e22.png)
Windows, selection does not span available space:

**Comment by StanWarford** [comment]
I see. It's fine now.
