### ISSUE TITLE
pep9asm memory dump splitter frozen

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#62]
The splitter to the left of the memory dump pane appears to be frozen.

**Comment by Matthew-McRaven** [comment]
@StanWarford was this fixed by my latest commit 30bb01faccee61040a976c22d151a5ff009f07f8?

**Comment by StanWarford** [comment]
Looks good. BTW, if you are going to ask me, don't close the issue so I can more conveniently reply!

**Comment by Matthew-McRaven** [comment]
I think when I reference the issue inn github in a commit message, it’s
closing the issue.

I’ll see if I can disable that bit of automation.
