### ISSUE TITLE
pep9asm Program Trace title no longer highlights

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#65]
The Program Trace title no longer highlights in blue when you click in it. See the new figures in Help -> Debugging Programs -> Tracing assembler code, and
qrc:/help-asm/images/fig0604trace1.png

**Comment by Matthew-McRaven** [comment]
Fixed this bug in 0eb9f9774732f3e2974dbe115196143e4d2a1a40.

**Comment by StanWarford** [comment]
Fixed.
