### ISSUE TITLE
pep9asm Main window label font sizes

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#68]
The label CPU is a bigger font size that all the other labels. I think the others are too small, and they should all be consistent with the CPU label.
<img width="471" alt="Pane-labels" src="https://user-images.githubusercontent.com/6937032/57565225-ca59f280-736e-11e9-9bfa-a304c1cb8258.png">

**Comment by Matthew-McRaven** [comment]
The CPU label being larger is the result of a bug in the CPU pane.
All other widgets respect the font (and size) specified by Pep::labelFont, where the CPU does not.
If you would like a larger font size universally, we need to modify the global Pep::labelFont, and verify that all UI's still appear correct.

**Comment by StanWarford** [comment]
Yes, modify the global labelFont.

**Comment by Matthew-McRaven** [comment]
This change affects all applications, so I've made these changes in the FontIncrease branch. Take a look at d28ba4cf480efa9f59a91785b20f4f1b34894e1d and see if you like the new look.

**Comment by StanWarford** [comment]
Yes, they are consistent now. There is too much discrepancy between the tab font and the pane font.
<img width="185" alt="tab-paane-fonts" src="https://user-images.githubusercontent.com/6937032/57746103-8aec1880-7684-11e9-8ce5-4b4323abe375.png">

**Comment by StanWarford** [comment]
So, can you make them bigger.

**Comment by Matthew-McRaven** [comment]
Did you switch over from the master branch to the FontIncrease branch?

Pictured below is a build from that branch, both fonts are 13pt (and are between 11-13px tall).
![Screen Shot 2019-05-14 at 8 21 58 PM](https://user-images.githubusercontent.com/35609985/57746415-fa163c80-7685-11e9-9f24-5c12b5620689.png)

**Comment by StanWarford** [comment]
Looks good on Windows. But here is Mac. I deleted the build folder and did a clean build from scratch.
<img width="361" alt="fork-setting" src="https://user-images.githubusercontent.com/6937032/57785897-6b3a0c00-76e7-11e9-8932-fdfbdb3d458e.png">
Here is the label compared to the tab font.
<img width="185" alt="font-size" src="https://user-images.githubusercontent.com/6937032/57786004-96246000-76e7-11e9-82db-cb100167e1cd.png">
Here is the label compared to the byte converter font.
![Uploading font-size-2.png…]()
Does your Mac build have the same small label font?

**Comment by StanWarford** [comment]
<img width="208" alt="font-size-2" src="https://user-images.githubusercontent.com/6937032/57786286-121ea800-76e8-11e9-8506-24cc663ef065.png">

**Comment by Matthew-McRaven** [comment]
It looks like you are still on the master branch, not FontIncrease. I merged the changes into master. Pull the changes and rebuild and let me know if that work.

**Comment by StanWarford** [comment]
Looks good now!
