### ISSUE TITLE
pep9cpu Dismiss error dialog request

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#73]
In Pep/9 CPU, when a unit test fails, and you dismiss the error dialog box, it would be good if the Microcode pane were automatically selected. That way, the error message would immediately be visible in red, without having to click inside the Microcode pane to select it. I will write the Help documentation assuming this feature.

**Comment by Matthew-McRaven** [comment]
@StanWarford is this working as you envisioned it?

**Comment by StanWarford** [comment]
Perfect!
