### ISSUE TITLE
Why Restart Debugging?

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#74]
I question the need for Debug->Restart Debugging in Pep9, Pep9CPU, and Pep9Micro. (1) It is a menu command with no corresponding tool icon or keyboard shortcut. (2) It appears to function as a Stop Debugging followed by a Start Debugging, which you can do with two toolbar clicks or two handy keyboard shortcuts, either of which is preferable to accessing a main menu item.
I recommend we delete it to simplify the user interface. What do you think?

**Comment by Matthew-McRaven** [comment]
I was adding it to keep parity with normal IDE operations.
I can see where it might not add a ton of value. so I have removed it in 8e1ca81ce1925fa4fe44c77535b8125becdd0a92.

**Comment by StanWarford** [comment]
Much better.
