### ISSUE TITLE
pep9cpu MemRead colors missing

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#75]
When MemRead is high, the data bus should be colored as in help-cpu/images/debugger7.png.
On the third read cycle, the data bus arrow should turn unidirectional as in help-cpu/images/debugger7.png.
See the incomplete Help->Debugging Use section to view the images.

**Comment by Matthew-McRaven** [comment]
@StanWarford, is this fixed with dbe85b44acb871d4a7811a7cc4e8fe08895459ff?

**Comment by StanWarford** [comment]
Perfect
