### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [StanWarford/pep9suite#77]
https://github.com/StanWarford/pep9suite/blob/c464c942e573ffb166bb4298e21680d94c28cba5/installer/installer-creator.pri#L42

Please provide an AppImage for download on GitHub Releases, thank you.

**Comment by Matthew-McRaven** [comment]
Downloads are provided via the book website, http://computersystemsbook.com. We are in the process of posting them.

**Comment by probonopd** [comment]
Thank you.

**Comment by Matthew-McRaven** [comment]
Appimages are now available to download from our releases page.

They are included [with or latest release](https://github.com/StanWarford/pep9suite/releases/tag/v9.2.0).
