### ISSUE TITLE
Pep9CPU inconsistent MDRMux highlighting.

### ISSUE THREAD

**Issue by Matthew-McRaven** [StanWarford/pep9suite#85]
MDRMux will not be highlighted unless MDRCk is set and there is a valid data flow through the MDRMux.

This is in contrast to the CMux, which will color itself and the C bus as long as there is valid data leaving CMux, even if that data is not clocked in to a register.

For consistency with the rest of the Pep9CPU application, all MDR multiplexers should be highlighted if data is flowing through them, even if the data value will not be clocked. More generally, every multiplexer in the application should have this behavior.

<img width="492" alt="Screen Shot 2019-11-21 at 00 30 35" src="https://user-images.githubusercontent.com/35609985/69306628-2a6f0280-0bf6-11ea-9201-a778d4924758.png">

This bug inconsistency is also present in the two-byte model with MDREMux, MDROMux.

**Comment by StanWarford** [comment]
Good observation. I agree all mux's should have this behavior.

**Comment by Matthew-McRaven** [comment]
Fixed with 71fe7aa6e5148a051a82f4d8128eedfad0f54d51.
