### ISSUE TITLE
Change to pep9term "cpuasm" mode

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#87]
The CPU model does not produce or use an external object file. The assembly language level does. The asm mode produces a .pepo file, which is then input for the run mode if no assembly errors occur.

It will make scripting much easier, and more consistent with the assembly level Asmb5, If the user specifies the name of an error log text file instead of an output log file. If there are no assembly errors, then no assembly error log is created. The script can test the existence of the error log instead of the content of an output log, which is not only easier but is consistent with the behavior of the asm mode.

**Comment by StanWarford** [comment]
Actually, to be consistent with the asm mode, the error log file name should be autogenerated by appending "_errLog.txt" to the source file name. This is also easier to script. The user does not have to specify an error log file name.

**Comment by Matthew-McRaven** [comment]
That sounds reasonable to me. I can put together a solution for this relatively quickly.

Should the "cpurun" mode function similarly by dropping the output flag?

**Comment by StanWarford** [comment]
Yes. If you stream the output to std out, the script can simply redirect it.

**Comment by Matthew-McRaven** [comment]
I made these changes to Pep9Term.

No text or file is generated when there are no errors.

Otherwise, the input file is used as a base name for the error log.

For convenience of those scripting Pep9Term, I added an -e option that
allows you to change the file path to the error log. This is necessary
since the figures exist in a non-writable directory.

**Comment by Matthew-McRaven** [comment]
The "releases" tab now has a new draft version implementing the new features. Pep10Term now has these interface changes as well.

**Comment by StanWarford** [comment]
The program does not terminate:

`Stans-iMac-Pro:collect16 warford$ pep9term cpurun --mc 01Prob1228.pepcpu -p Prob1228-Unit-1.pepcpu
Program assembled successfully.
Preconditions assembled successfully.
Passed unit tests.
^C`

I must <ctrl-c> to terminate

**Comment by Matthew-McRaven** [comment]
Can you email me the file?

**Comment by StanWarford** [comment]
Done. Also, I cannot redirect the output. Is it streamed to std out?

**Comment by Matthew-McRaven** [comment]
I think it’s streaming to STDERR via qDebug, let me check.

**Comment by Matthew-McRaven** [comment]
On Windows, the process terminates correctly. On my Mac, running OS X 10.14.6 and Qt 5.13.2, the given program terminates.

Did you build from the sources, or did you use one of my provided images?

**Comment by StanWarford** [comment]
It is terminating correctly now with no apparent changes. Still cannot redirect output.

**Comment by Matthew-McRaven** [comment]
What are you redirecting output to? The modes “asm” and “run” supposedly
generate no redirectable output, and the newer modes follow this design.

**Comment by StanWarford** [comment]
OK, now I see. I used the -o option with asm mode. I thought I had redirected output. I will use -o. Should be fine.

**Comment by Matthew-McRaven** [comment]
There is no -o option, since the CPU generates no output. The CPU cannot
generate any output (no memory mapped io at the CPU later), and we have no
object code format.

The only option is to generate errors, either syntax errors or post
condition errors.

In either case, they go to the error log.

**Comment by StanWarford** [comment]
OK, makes sense. So my script will check for the existence of the error log and will either use it or echo it's own "success" text.

**Comment by StanWarford** [comment]
I injected a run-time error in a .pepcpu file and pep9term crashed:

Program assembled successfully.
Preconditions assembled successfully.
Data section reporting an error
The CPU failed for the following reason:  No value on C Bus to clock in.
QIODevice::write (QFile, "/Users/warford/Documents/Classes/cs425/collect/collect16/01Prob1228_errLog.txt"): device not open

Here's the source file. Error is on line 10. Should be AMux=0

[01Prob1228.pepcpu.txt](https://github.com/StanWarford/pep9suite/files/4007865/01Prob1228.pepcpu.txt)

**Comment by Matthew-McRaven** [comment]
I think I fixed the bug in 2a6ef7905a283ce5b4a3916b0ae6603132824c9f.
I'll have uploaded the new version of Pep9Term to the "releases" tab.

**Comment by StanWarford** [comment]
Tested OK. Looks good.
