### ISSUE TITLE
pep9term error with correct program

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#90]
The attached program is correct and passes the unit test in pep9cpu, but fails in pep9term with the following message:

Stans-iMac-Pro:collect16 warford$ ./onetest.sh 99
Compiling cs330-99Prob1228
Program assembled successfully.
Testing 99Prob1228.pepcpu
Program assembled successfully.
Preconditions assembled successfully.
Default start symbol did not exists:  "start"
Data section reporting an error.
The CPU failed for the following reason:  MARMux has no output but MARCk.

[99prob1228.pepcpu.txt](https://github.com/StanWarford/pep9suite/files/4022860/99prob1228.pepcpu.txt)

**Comment by Matthew-McRaven** [comment]
I think I messed up some configuration flags. Try invoking the program
again with the addition of the --d1 flag and let me know the results?

**Comment by StanWarford** [comment]
Same thing with --d1 flag.

**Comment by StanWarford** [comment]
Here is my onetest.sh file
[onetest.sh.txt](https://github.com/StanWarford/pep9suite/files/4027978/onetest.sh.txt)

**Comment by Matthew-McRaven** [comment]
I think this is helped by 2b88ed0a8f989ddc1021ae0afcfc65b992296896.

I reversed a boolean condition for the control of the two-byte bus, leading to this bug.

**Comment by Matthew-McRaven** [comment]
Fixed with 9bcaef52dad31ade697ada4d1f6aa54cf0efbe58 and merged into master
