### ISSUE TITLE
pep9cpu does not open source

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#91]
Double clicking a .pepcpu file opens the pep9cpu app, but does not open the file in the microcode pane.

**Comment by StanWarford** [comment]
Cancel. I was not testing with the latest build.

**Comment by StanWarford** [comment]
This is an issue. It opens in pep8cpu fine, but not pep9cpu.

**Comment by Matthew-McRaven** [comment]
I believe this issue may apply to all applications in the Pep9 Suite. I’ll
take a look on Monday and let you know what I find out

**Comment by Matthew-McRaven** [comment]
I believe this is fixed by 95271737bf014ce3f9d9ec014ff55c6a28c50b21.

If you need, I can build a version of Pep9CPU and post the image for you to test.

**Comment by Matthew-McRaven** [comment]
On my Mac, the feature works as anticipated with the new commit across all Pep/9 applications. 

I have posted images under our release drafts that fix this problem for Pep9, Pep9Micro, and Pep9CPU for Mac OS.

**Comment by StanWarford** [comment]
I downloaded the release draft for Pep/9. Crashed on double clicking the source file with the following crash log:

Process:               Pep9 [93566]
Path:                  /Users/USER/*/Pep9.app/Contents/MacOS/Pep9
Identifier:            edu.cslab.pep9
Version:               47
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Pep9 [93566]
User ID:               501

Date/Time:             2020-01-09 16:22:32.187 -0800
OS Version:            Mac OS X 10.14.6 (18G2022)
Report Version:        12
Anonymous UUID:        CCF2B973-971B-B6C5-FDE6-096FEF2E1729


Time Awake Since Boot: 1200000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtWebEngineWidgets.framework/Versions/5/QtWebEngineWidgets
  Referenced from: /Users/USER/*/Pep9.app/Contents/MacOS/Pep9
  Reason: image not found

Binary Images:
       0x10030e000 -        0x1006c9ff7 +edu.cslab.pep9 (47) <0C107C57-5A5B-3EE7-BF65-07477F702CA3> /Users/USER/*/Pep9.app/Contents/MacOS/Pep9
       0x10c69e000 -        0x10c70870f  dyld (655.1.1) <B3D9DDCB-5AA7-3674-9608-16B5AA4AA494> /usr/lib/dyld
    0x7fff3cfcb000 -     0x7fff3dd80ffb  com.apple.AppKit (6.9 - 1671.60.109) <E23B2968-32EA-340D-9E5E-12F5370DC55D> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff41c39000 -     0x7fff41fe6ffb  com.apple.Foundation (6.9 - 1575.23) <C5EA5ABE-2E0C-37A0-A02A-F3150FE3CC66> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

Model: iMac17,1, BootROM 170.0.0.0.0, 4 processors, Intel Core i7, 4 GHz, 32 GB, SMC 2.34f2
Graphics: kHW_AMDRadeonR9M395XItem, AMD Radeon R9 M395X, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x484D54343147533642465238412D52442020
Memory Module: BANK 0/DIMM1, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x484D54343147533642465238412D52442020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x484D54343147533642465238412D52442020
Memory Module: BANK 1/DIMM1, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x484D54343147533642465238412D52442020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x14A), Broadcom BCM43xx 1.0 (7.77.61.3 AirPortDriverBrcmNIC-1305.9)
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: pci105a,8760, RAID Controller, Thunderbolt@193,0,0
Serial ATA Device: APPLE SSD SM1024G, 1 TB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: Magic Trackpad 2
Thunderbolt Bus: iMac, Apple Inc., 28.1
Thunderbolt Device: Pegasus2-R, Promise Technology, Inc., 1, 19.2

**Comment by Matthew-McRaven** [comment]
Well, looks like my installer didn’t grab all the right libraries.

Let me try that again.

**Comment by StanWarford** [comment]
I downloaded the release draft for Pep/9 CPU. File->Open worked correctly. However, double clicking opened the app without loading the source.

**Comment by Matthew-McRaven** [comment]
I believe you have an old copy of Pep9CPU on your machine.

After I deleted all existing copies of Pep9CPU from my machine and installed the image posted on the draft release, double-clicking on a file opened it correctly inside of Pep9CPU.

**Comment by Matthew-McRaven** [comment]
Issue appears to be resolved.

**Comment by Matthew-McRaven** [comment]
Apparently this is still ongoing. Must continue to debug.
