### ISSUE TITLE
pep9asm Assemble & Format looses text

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#92]
Copy to Source, Figure 5.10
Run
Edit Source
Select Assemble & Format
Original, not edited, source is assembled
<img width="438" alt="Screen Shot 2020-02-04 at 8 09 34 PM" src="https://user-images.githubusercontent.com/6937032/73810374-2ed5a100-478b-11ea-8772-c4df98ae58a6.png">

<img width="438" alt="Screen Shot 2020-02-04 at 8 10 40 PM" src="https://user-images.githubusercontent.com/6937032/73810396-3c8b2680-478b-11ea-9dff-23405916b64d.png">

<img width="438" alt="Screen Shot 2020-02-04 at 8 11 08 PM" src="https://user-images.githubusercontent.com/6937032/73810405-457bf800-478b-11ea-937e-b94419ec20f8.png">

<img width="438" alt="Screen Shot 2020-02-04 at 8 11 29 PM" src="https://user-images.githubusercontent.com/6937032/73810417-4f9df680-478b-11ea-88ab-3e2fa282686c.png">

**Comment by Matthew-McRaven** [comment]
Should be fixed in f3ea22a8fe2734daf2bea53395c449ccdf1d821e.

**Comment by StanWarford** [comment]
Works now
