### ISSUE TITLE
pep9asm object code trace does not display memory dump

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#93]
Clear memory
Copy to Object Figure 4.23
Select Debug -> Start Debugging Object
Can single step, but Memory does not display loaded object code
<img width="670" alt="Screen Shot 2020-02-04 at 8 24 18 PM" src="https://user-images.githubusercontent.com/6937032/73810768-5aa55680-478c-11ea-9a65-667f664c502c.png">

**Comment by Matthew-McRaven** [comment]
Should be fixed in 8057c13df8bae36844bee0d15a5200a8425224c7, on the "rescale-mempane" branch.

**Comment by StanWarford** [comment]
Works now
