### ISSUE TITLE
pep9cpu Clear CPU

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#95]
In pep9cpu, System -> Clear CPU does not clear the MDR.

Also, if MDR has a nonzero value in it, and you interactively execute

A=22, AMux=1, ALU=0, CMux=1, MDRMux=1; MDRCk

the MDR is not cleared.d

**Comment by Matthew-McRaven** [comment]
Should be fixed in 1942b00464e8c7c9340f6584d6a2ac6ffa2a0755. This commit is on Master.
