### ISSUE TITLE
pep9cpu Copy to Microcode

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#96]
Interactive settings that contain MDRMux or MDRCk do not Copy to Microcode.

**Comment by Matthew-McRaven** [comment]
Should be fixed in 1942b00464e8c7c9340f6584d6a2ac6ffa2a0755. This commit is on Master.

**Comment by Matthew-McRaven** [comment]
@StanWarford Can we close both this and #95?
