### ISSUE TITLE
Trace tag #2d should assume signed integer

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#98]
Trace tag #2d displays unsigned value in Pep/9

<img width="356" alt="Screen Shot 2020-04-22 at 12 40 32 PM" src="https://user-images.githubusercontent.com/6937032/80026778-8e447280-8497-11ea-92c9-15462efa69d7.png">

Should assume signed value as in Pep/8

<img width="356" alt="Screen Shot 2020-04-22 at 12 40 13 PM" src="https://user-images.githubusercontent.com/6937032/80026824-9dc3bb80-8497-11ea-9ddf-17ee6d18d2e1.png">

The CPU value is rendered correctly in Pep/9

<img width="307" alt="Screen Shot 2020-04-22 at 12 50 19 PM" src="https://user-images.githubusercontent.com/6937032/80027004-f09d7300-8497-11ea-8070-6f79c7f61ab1.png">

**Comment by Matthew-McRaven** [comment]
For 1D tags, do we want them to be signed bytes or unsigned bytes?

**Comment by StanWarford** [comment]
Unsigned

**Comment by Matthew-McRaven** [comment]
I believe this to be fixed in acaa582999e1b07e3a5a51a9205e7d8db03aac17 on memorytrace-fixes.

**Comment by StanWarford** [comment]
Fixed.
