### ISSUE TITLE
Memory trace does not model the heap data in a consecutive order

### ISSUE THREAD

**Issue by pnicklet** [StanWarford/pep9suite#99]
A memory trace on a program that uses dynamic memory allocation with the appropriate "#allocate" trace tags, such as Figure 6.48, does not represent the data on the heap in a consecutive order. Though the displayed address and content of each cell are correct, the cells in each individual data frame should be in reverse order.

![issue](https://user-images.githubusercontent.com/64160583/80019309-2d636d00-848c-11ea-8df8-e413b8ef9cf4.PNG)

Running Pep9 v9.2

**Comment by Matthew-McRaven** [comment]
I believe this should be fixed by aecdcdf437e19f4a56a658489c114f7043f032cd.

Here's a sample output from Fig 6.48
<img width="161" alt="Screen Shot 2020-04-23 at 08 48 07" src="https://user-images.githubusercontent.com/35609985/80119959-37927380-853f-11ea-9a8e-60204fd8b576.png">

**Comment by StanWarford** [comment]
Fixed.
